# Generated by Django 2.1.4 on 2018-12-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMatchingFuels',
            fields=[
                ('fuel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_fuel_id', models.IntegerField(blank=True, null=True)),
                ('fuel_uch_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_matching_fuels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DMatchingStation',
            fields=[
                ('service_station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('azs_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_matching_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DStationFuelPrices',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel_type_id', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_station_fuel_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('mobile_device_id', models.IntegerField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=128)),
                ('satisfaction_level', models.SmallIntegerField()),
                ('subject', models.SmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('photo', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('fuel_id', models.SmallIntegerField()),
                ('active', models.BooleanField()),
                ('version_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=16)),
                ('external_system_id', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('price_retail', models.FloatField()),
            ],
            options={
                'db_table': 'fuel_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_abbr', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoyalInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position_id', models.SmallIntegerField()),
                ('active', models.BooleanField()),
                ('version_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('rule', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('full_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'loyal_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('is_read', models.BooleanField()),
                ('version_id', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('internal_description', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(max_length=255)),
                ('pre_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('short_review', models.CharField(max_length=255)),
                ('company_site_url', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageImg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resolution_id', models.SmallIntegerField()),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'message_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriprion', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'message_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageTypeImg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resolution_id', models.SmallIntegerField()),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'message_type_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField()),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('push_device_registration_token', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'mobile_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('version_id', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('internal_description', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField()),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resolution_id', models.SmallIntegerField()),
                ('preview_img_url', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'news_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('version_id', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('internal_description', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField()),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'partner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('map_longitude', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
            options={
                'db_table': 'partner_coordinates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.BigIntegerField()),
                ('lang_abbr', models.CharField(max_length=2)),
                ('preview_img_url', models.CharField(max_length=255)),
                ('short_review', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('company_site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=16000)),
            ],
            options={
                'db_table': 'partner_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerImg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resolution_id', models.SmallIntegerField()),
                ('preview_img_url', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'partner_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('version_id', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('internal_description', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.BooleanField()),
            ],
            options={
                'db_table': 'promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionImg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resolution_id', models.SmallIntegerField()),
                ('preview_img_url', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'promotion_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id_service_station', models.IntegerField(primary_key=True, serialize=False)),
                ('version_id', models.BigIntegerField(blank=True, null=True)),
                ('id_clients', models.IntegerField(blank=True, null=True)),
                ('id_brands', models.IntegerField(blank=True, null=True)),
                ('fuel_types', models.IntegerField()),
                ('services', models.IntegerField()),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('n_service_station', models.CharField(blank=True, max_length=50, null=True)),
                ('kn_service_station', models.CharField(blank=True, max_length=25, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('area', models.CharField(blank=True, max_length=30, null=True)),
                ('place', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('pos_address', models.CharField(blank=True, max_length=100, null=True)),
                ('pos_index', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('azs_code', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'service_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceStationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_service_station', models.CharField(max_length=50)),
                ('kn_service_station', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service_station_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('service_id', models.SmallIntegerField()),
                ('active', models.BooleanField()),
                ('version_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=16)),
                ('external_system_id', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=128, unique=True)),
                ('last_version', models.BigIntegerField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('is_extended_version', models.BooleanField()),
            ],
            options={
                'db_table': 'sync_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyncStateByLang',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=128)),
                ('last_version', models.BigIntegerField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('is_extended_version', models.BooleanField()),
            ],
            options={
                'db_table': 'sync_state_by_lang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsEn',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_api.News')),
                ('preview_img_url', models.CharField(max_length=255)),
                ('short_review', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('company_site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=16000)),
            ],
            options={
                'db_table': 'news_en',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsRu',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_api.News')),
                ('preview_img_url', models.CharField(max_length=255)),
                ('short_review', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('company_site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=16000)),
            ],
            options={
                'db_table': 'news_ru',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsUk',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_api.News')),
                ('preview_img_url', models.CharField(max_length=255)),
                ('short_review', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('company_site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=16000)),
            ],
            options={
                'db_table': 'news_uk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionEn',
            fields=[
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_api.Promotion')),
                ('preview_img_url', models.CharField(max_length=255)),
                ('short_review', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('company_site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=16000)),
            ],
            options={
                'db_table': 'promotion_en',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionRu',
            fields=[
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_api.Promotion')),
                ('preview_img_url', models.CharField(max_length=255)),
                ('short_review', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('company_site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=16000)),
            ],
            options={
                'db_table': 'promotion_ru',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionUk',
            fields=[
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_api.Promotion')),
                ('preview_img_url', models.CharField(max_length=255)),
                ('short_review', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('company_site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(max_length=16000)),
            ],
            options={
                'db_table': 'promotion_uk',
                'managed': False,
            },
        ),
    ]
