# Generated by Django 2.1.5 on 2019-01-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False, 'ordering': ['-created_time'], 'verbose_name': 'Новости'},
        ),
    ]
