# Generated by Django 2.1.5 on 2019-02-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0002_auto_20190129_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True},
        ),
    ]
