# Generated by Django 2.1.5 on 2019-02-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0003_auto_20190206_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
    ]
